### ISSUE TITLE
requirements.txt numpy==1.26.4 fails to build on Python 3.13 with M1 Mac

### ISSUE THREAD

**Issue by sidhantm123** [TinyTapeout/tt-support-tools#165]
the requirements.txt header states "# This file is autogenerated by pip-compile with Python 3.13"
but numpy==1.26.4 doesn't support python 3.13

Here is the full error Im getting:
Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error

× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1

In file included from ../numpy/core/src/npymath/halffloat.cpp:12:
In file included from ../numpy/core/src/common/common.hpp:8:
../numpy/core/src/common/utils.hpp:10:10: fatal error: 'type_traits' file not found
   10 | #include <type_traits>

Should I install requirements with python 3.12?

**Comment by sidhantm123** [comment]
re ran with python3.12 and it worked!
